name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          yarn install
          yarn add -D vuepress-theme-hope@1.27.1
          
      - name: build
        run: yarn build
          
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          build_dir: docs/.vuepress/dist
          fqdn: pixeltail-wiki.owo.fit
          keep_history: true
